[project]
name = "eh-fifty"
dependencies = [
  "pyusb>=1.2.1,<2",
]
authors = [
  { name="Tom Dryer", email="tomdryer.com@gmail.com" },
]
description = "Library for configuring the Astro A50 wireless headset and base station (generation 4)"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dynamic = ["version"]

[project.urls]
"Homepage" = "https://github.com/tdryer/eh-fifty"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["eh_fifty"]

[tool.setuptools.dynamic]
version = {attr = "eh_fifty.__version__"}

[dependency-groups]
dev = [
  "mypy",
  "pytest",
  "ruff>=0.16.8",
]

[tool.uv.dependency-groups]
dev = {requires-python = ">=3.10"}

[tool.ruff.lint]
extend-select = ["D100", "D101", "D102", "D103"]
ignore = [
    "PYI034",
]

[tool.ruff.lint.per-file-ignores]
"tests.py" = ["D103"]

[tool.mypy]
strict = true

[[tool.mypy.overrides]]
module = "usb.*"
ignore_missing_imports = true
